// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("swok8sdiscovery")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector-contrib/receiver/swok8sdiscovery"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
