// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for mqtt metrics.
type MetricsConfig struct {
	SwOtelcolIoTRoundtrip MetricConfig `mapstructure:"sw.otelcol.IoT.roundtrip"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SwOtelcolIoTRoundtrip: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for mqtt resource attributes.
type ResourceAttributesConfig struct {
	SwOtelcolIotBrokerHost     ResourceAttributeConfig `mapstructure:"sw.otelcol.IotBroker.host"`
	SwOtelcolIotBrokerName     ResourceAttributeConfig `mapstructure:"sw.otelcol.IotBroker.name"`
	SwOtelcolIotBrokerPort     ResourceAttributeConfig `mapstructure:"sw.otelcol.IotBroker.port"`
	SwOtelcolIotBrokerProtocol ResourceAttributeConfig `mapstructure:"sw.otelcol.IotBroker.protocol"`
	SwOtelcolIotBrokerStatus   ResourceAttributeConfig `mapstructure:"sw.otelcol.IotBroker.status"`
	SwOtelcolIotSensorName     ResourceAttributeConfig `mapstructure:"sw.otelcol.IotSensor.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		SwOtelcolIotBrokerHost: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolIotBrokerName: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolIotBrokerPort: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolIotBrokerProtocol: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolIotBrokerStatus: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolIotSensorName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for mqtt metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
