// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetSwOtelcolIotBrokerHost("sw.otelcol.IotBroker.host-val")
			rb.SetSwOtelcolIotBrokerName("sw.otelcol.IotBroker.name-val")
			rb.SetSwOtelcolIotBrokerPort(25)
			rb.SetSwOtelcolIotBrokerProtocolMqtt()
			rb.SetSwOtelcolIotBrokerStatusOK()
			rb.SetSwOtelcolIotSensorName("sw.otelcol.IotSensor.name-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 6, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 6, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("sw.otelcol.IotBroker.host")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.IotBroker.host-val", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.IotBroker.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.IotBroker.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.IotBroker.port")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, 25, val.Int())
			}
			val, ok = res.Attributes().Get("sw.otelcol.IotBroker.protocol")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "mqtt", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.IotBroker.status")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "OK", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.IotSensor.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.IotSensor.name-val", val.Str())
			}
		})
	}
}
