// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for mqtt metrics.
type MetricsConfig struct {
	SwOtelcolMqttBrokerActiveSubscriptions       MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.active_subscriptions"`
	SwOtelcolMqttBrokerBytesReceivedPerMinute    MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.bytes_received_per_minute"`
	SwOtelcolMqttBrokerBytesSentPerMinute        MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.bytes_sent_per_minute"`
	SwOtelcolMqttBrokerClientsConnected          MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.clients_connected"`
	SwOtelcolMqttBrokerMessagesReceivedPerMinute MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.messages_received_per_minute"`
	SwOtelcolMqttBrokerMessagesSentPerMinute     MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.messages_sent_per_minute"`
	SwOtelcolMqttBrokerRoundtrip                 MetricConfig `mapstructure:"sw.otelcol.mqtt.broker.roundtrip"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SwOtelcolMqttBrokerActiveSubscriptions: MetricConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerBytesReceivedPerMinute: MetricConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerBytesSentPerMinute: MetricConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerClientsConnected: MetricConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerMessagesReceivedPerMinute: MetricConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerMessagesSentPerMinute: MetricConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerRoundtrip: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for mqtt resource attributes.
type ResourceAttributesConfig struct {
	SwOtelcolMqttBrokerName     ResourceAttributeConfig `mapstructure:"sw.otelcol.mqtt.broker.name"`
	SwOtelcolMqttBrokerPort     ResourceAttributeConfig `mapstructure:"sw.otelcol.mqtt.broker.port"`
	SwOtelcolMqttBrokerProtocol ResourceAttributeConfig `mapstructure:"sw.otelcol.mqtt.broker.protocol"`
	SwOtelcolMqttBrokerServer   ResourceAttributeConfig `mapstructure:"sw.otelcol.mqtt.broker.server"`
	SwOtelcolMqttBrokerStatus   ResourceAttributeConfig `mapstructure:"sw.otelcol.mqtt.broker.status"`
	SwOtelcolMqttSensorName     ResourceAttributeConfig `mapstructure:"sw.otelcol.mqtt.sensor.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		SwOtelcolMqttBrokerName: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerPort: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerProtocol: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerServer: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolMqttBrokerStatus: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolMqttSensorName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for mqtt metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
