// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("mqtt")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector-releases/receiver/mqttreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
