// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetSwOtelcolMqttBrokerName("sw.otelcol.MqttBroker.name-val")
			rb.SetSwOtelcolMqttBrokerPort(26)
			rb.SetSwOtelcolMqttBrokerProtocolMqtt()
			rb.SetSwOtelcolMqttBrokerServer("sw.otelcol.MqttBroker.server-val")
			rb.SetSwOtelcolMqttBrokerStatusOK()
			rb.SetSwOtelcolMqttSensorName("sw.otelcol.MqttSensor.name-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 6, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 6, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("sw.otelcol.MqttBroker.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.MqttBroker.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.MqttBroker.port")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, 26, val.Int())
			}
			val, ok = res.Attributes().Get("sw.otelcol.MqttBroker.protocol")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "mqtt", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.MqttBroker.server")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.MqttBroker.server-val", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.MqttBroker.status")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "OK", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.MqttSensor.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.MqttSensor.name-val", val.Str())
			}
		})
	}
}
