// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	SwOtelcolMqttRoundtrip: metricInfo{
		Name: "sw.otelcol.Mqtt.Roundtrip",
	},
}

type metricsInfo struct {
	SwOtelcolMqttRoundtrip metricInfo
}

type metricInfo struct {
	Name string
}

type metricSwOtelcolMqttRoundtrip struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills sw.otelcol.Mqtt.Roundtrip metric with initial data.
func (m *metricSwOtelcolMqttRoundtrip) init() {
	m.data.SetName("sw.otelcol.Mqtt.Roundtrip")
	m.data.SetDescription("Roundtrip time to the Mqtt Broker")
	m.data.SetUnit("millisecond")
	m.data.SetEmptyGauge()
}

func (m *metricSwOtelcolMqttRoundtrip) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricSwOtelcolMqttRoundtrip) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricSwOtelcolMqttRoundtrip) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricSwOtelcolMqttRoundtrip(cfg MetricConfig) metricSwOtelcolMqttRoundtrip {
	m := metricSwOtelcolMqttRoundtrip{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricSwOtelcolMqttRoundtrip   metricSwOtelcolMqttRoundtrip
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricSwOtelcolMqttRoundtrip:   newMetricSwOtelcolMqttRoundtrip(mbc.Metrics.SwOtelcolMqttRoundtrip),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.MqttBroker.name"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerName.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.MqttBroker.name"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerName.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerPort.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.MqttBroker.port"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerPort.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerPort.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.MqttBroker.port"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerPort.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerProtocol.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.MqttBroker.protocol"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerProtocol.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerProtocol.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.MqttBroker.protocol"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerProtocol.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerServer.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.MqttBroker.server"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerServer.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerServer.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.MqttBroker.server"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerServer.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerStatus.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.MqttBroker.status"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerStatus.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttBrokerStatus.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.MqttBroker.status"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttBrokerStatus.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttSensorName.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.MqttSensor.name"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttSensorName.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolMqttSensorName.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.MqttSensor.name"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolMqttSensorName.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricSwOtelcolMqttRoundtrip.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordSwOtelcolMqttRoundtripDataPoint adds a data point to sw.otelcol.Mqtt.Roundtrip metric.
func (mb *MetricsBuilder) RecordSwOtelcolMqttRoundtripDataPoint(ts pcommon.Timestamp, val float64) {
	mb.metricSwOtelcolMqttRoundtrip.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
