// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetSwOtelcolMqttBrokerName("sw.otelcol.mqtt.broker.name-val")
			rb.SetSwOtelcolMqttBrokerPort(27)
			rb.SetSwOtelcolMqttBrokerProtocolMqtt()
			rb.SetSwOtelcolMqttBrokerServer("sw.otelcol.mqtt.broker.server-val")
			rb.SetSwOtelcolMqttBrokerStatusOK()
			rb.SetSwOtelcolMqttSensorName("sw.otelcol.mqtt.sensor.name-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 6, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 6, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("sw.otelcol.mqtt.broker.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.mqtt.broker.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.mqtt.broker.port")
			assert.True(t, ok)
			if ok {
				assert.EqualValues(t, 27, val.Int())
			}
			val, ok = res.Attributes().Get("sw.otelcol.mqtt.broker.protocol")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "mqtt", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.mqtt.broker.server")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.mqtt.broker.server-val", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.mqtt.broker.status")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "OK", val.Str())
			}
			val, ok = res.Attributes().Get("sw.otelcol.mqtt.sensor.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "sw.otelcol.mqtt.sensor.name-val", val.Str())
			}
		})
	}
}
