version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: saturday
    commit-message:
      prefix: "chore: "

  - package-ecosystem: gomod
    directories:
      - "/connector/*/"
      - "/exporter/*/"
      - "/extension/*/"
      - "/internal/*/"
      - "/pkg/*/"
      - "/processor/*/"
      - "/receiver/*/"
      - "/cmd/*/"
    schedule:
      interval: weekly
      day: sunday
      time: "03:30"
    allow:
      - dependency-type: "direct"
    ignore:
      # these are to be handled by opentelemtery bumps, and releases
      - dependency-name: "*opentelemetry*"
      - dependency-name: "*solarwinds-otel-collector*"
      # k8s.io bumps must be tightly bound to bumps of opentelemetry dependencies, 
      # bumping them independently results in build failures due to incompatibility
      - dependency-name: "*k8s.io*"
    groups:
      components-security:
        applies-to: security-updates
        patterns:
          - "*"
        exclude-patterns:
          - "*opentelemetry*"
          - "*solarwinds-otel-collector*"
          - "*k8s.io*"
        update-types:
          - "patch"
          - "minor"
    commit-message:
      prefix: "chore: "
