// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("dnsquery")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector-contrib/receiver/dnsqueryreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
