// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordDNSQueryQueryTimeMsDataPoint(ts, 1, "dns_query.domain-val", "dns_query.rcode-val", "dns_query.record_type-val", "dns_query.result-val", "dns_query.server-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordDNSQueryRcodeValueDataPoint(ts, 1, "dns_query.domain-val", "dns_query.rcode-val", "dns_query.record_type-val", "dns_query.result-val", "dns_query.server-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordDNSQueryResultCodeDataPoint(ts, 1, "dns_query.domain-val", "dns_query.rcode-val", "dns_query.record_type-val", "dns_query.result-val", "dns_query.server-val")

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "dns_query.query_time_ms":
					assert.False(t, validatedMetrics["dns_query.query_time_ms"], "Found a duplicate in the metrics slice: dns_query.query_time_ms")
					validatedMetrics["dns_query.query_time_ms"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The time taken to complete the DNS query in milliseconds. Zero on timeout or error.", mi.Description())
					assert.Equal(t, "ms", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					dnsQueryDomainAttrVal, ok := dp.Attributes().Get("dns_query.domain")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.domain-val", dnsQueryDomainAttrVal.Str())
					dnsQueryRcodeAttrVal, ok := dp.Attributes().Get("dns_query.rcode")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.rcode-val", dnsQueryRcodeAttrVal.Str())
					dnsQueryRecordTypeAttrVal, ok := dp.Attributes().Get("dns_query.record_type")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.record_type-val", dnsQueryRecordTypeAttrVal.Str())
					dnsQueryResultAttrVal, ok := dp.Attributes().Get("dns_query.result")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.result-val", dnsQueryResultAttrVal.Str())
					dnsQueryServerAttrVal, ok := dp.Attributes().Get("dns_query.server")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.server-val", dnsQueryServerAttrVal.Str())
				case "dns_query.rcode_value":
					assert.False(t, validatedMetrics["dns_query.rcode_value"], "Found a duplicate in the metrics slice: dns_query.rcode_value")
					validatedMetrics["dns_query.rcode_value"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The numeric DNS response code (rcode). 0=NOERROR, 3=NXDOMAIN, etc. Zero on timeout or error.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					dnsQueryDomainAttrVal, ok := dp.Attributes().Get("dns_query.domain")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.domain-val", dnsQueryDomainAttrVal.Str())
					dnsQueryRcodeAttrVal, ok := dp.Attributes().Get("dns_query.rcode")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.rcode-val", dnsQueryRcodeAttrVal.Str())
					dnsQueryRecordTypeAttrVal, ok := dp.Attributes().Get("dns_query.record_type")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.record_type-val", dnsQueryRecordTypeAttrVal.Str())
					dnsQueryResultAttrVal, ok := dp.Attributes().Get("dns_query.result")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.result-val", dnsQueryResultAttrVal.Str())
					dnsQueryServerAttrVal, ok := dp.Attributes().Get("dns_query.server")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.server-val", dnsQueryServerAttrVal.Str())
				case "dns_query.result_code":
					assert.False(t, validatedMetrics["dns_query.result_code"], "Found a duplicate in the metrics slice: dns_query.result_code")
					validatedMetrics["dns_query.result_code"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "The result code of the DNS query: 0=success, 1=timeout, 2=error.", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					dnsQueryDomainAttrVal, ok := dp.Attributes().Get("dns_query.domain")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.domain-val", dnsQueryDomainAttrVal.Str())
					dnsQueryRcodeAttrVal, ok := dp.Attributes().Get("dns_query.rcode")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.rcode-val", dnsQueryRcodeAttrVal.Str())
					dnsQueryRecordTypeAttrVal, ok := dp.Attributes().Get("dns_query.record_type")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.record_type-val", dnsQueryRecordTypeAttrVal.Str())
					dnsQueryResultAttrVal, ok := dp.Attributes().Get("dns_query.result")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.result-val", dnsQueryResultAttrVal.Str())
					dnsQueryServerAttrVal, ok := dp.Attributes().Get("dns_query.server")
					assert.True(t, ok)
					assert.Equal(t, "dns_query.server-val", dnsQueryServerAttrVal.Str())
				}
			}
		})
	}
}
