// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for dnsquery metrics.
type MetricsConfig struct {
	DNSQueryQueryTimeMs MetricConfig `mapstructure:"dns_query.query_time_ms"`
	DNSQueryRcodeValue  MetricConfig `mapstructure:"dns_query.rcode_value"`
	DNSQueryResultCode  MetricConfig `mapstructure:"dns_query.result_code"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DNSQueryQueryTimeMs: MetricConfig{
			Enabled: true,
		},
		DNSQueryRcodeValue: MetricConfig{
			Enabled: true,
		},
		DNSQueryResultCode: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for dnsquery metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
