// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for dnsquery metrics.
type MetricsConfig struct {
	DNSQueryQueryTimeMs MetricConfig `mapstructure:"dns_query.query_time_ms"`
	DNSQueryRcodeValue  MetricConfig `mapstructure:"dns_query.rcode_value"`
	DNSQueryResultCode  MetricConfig `mapstructure:"dns_query.result_code"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DNSQueryQueryTimeMs: MetricConfig{
			Enabled: true,
		},
		DNSQueryRcodeValue: MetricConfig{
			Enabled: true,
		},
		DNSQueryResultCode: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for dnsquery resource attributes.
type ResourceAttributesConfig struct {
	SwOtelcolDnsqueryDomain     ResourceAttributeConfig `mapstructure:"sw.otelcol.dnsquery.domain"`
	SwOtelcolDnsqueryRecordType ResourceAttributeConfig `mapstructure:"sw.otelcol.dnsquery.record_type"`
	SwOtelcolDnsqueryServer     ResourceAttributeConfig `mapstructure:"sw.otelcol.dnsquery.server"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		SwOtelcolDnsqueryDomain: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolDnsqueryRecordType: ResourceAttributeConfig{
			Enabled: true,
		},
		SwOtelcolDnsqueryServer: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for dnsquery metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
