// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetSwOtelcolDnsqueryDomain sets provided value as "sw.otelcol.dnsquery.domain" attribute.
func (rb *ResourceBuilder) SetSwOtelcolDnsqueryDomain(val string) {
	if rb.config.SwOtelcolDnsqueryDomain.Enabled {
		rb.res.Attributes().PutStr("sw.otelcol.dnsquery.domain", val)
	}
}

// SetSwOtelcolDnsqueryRecordType sets provided value as "sw.otelcol.dnsquery.record_type" attribute.
func (rb *ResourceBuilder) SetSwOtelcolDnsqueryRecordType(val string) {
	if rb.config.SwOtelcolDnsqueryRecordType.Enabled {
		rb.res.Attributes().PutStr("sw.otelcol.dnsquery.record_type", val)
	}
}

// SetSwOtelcolDnsqueryServer sets provided value as "sw.otelcol.dnsquery.server" attribute.
func (rb *ResourceBuilder) SetSwOtelcolDnsqueryServer(val string) {
	if rb.config.SwOtelcolDnsqueryServer.Enabled {
		rb.res.Attributes().PutStr("sw.otelcol.dnsquery.server", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
