// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	DNSQueryQueryTimeMs: metricInfo{
		Name: "dns_query.query_time_ms",
	},
	DNSQueryRcodeValue: metricInfo{
		Name: "dns_query.rcode_value",
	},
	DNSQueryResultCode: metricInfo{
		Name: "dns_query.result_code",
	},
}

type metricsInfo struct {
	DNSQueryQueryTimeMs metricInfo
	DNSQueryRcodeValue  metricInfo
	DNSQueryResultCode  metricInfo
}

type metricInfo struct {
	Name string
}

type metricDNSQueryQueryTimeMs struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills dns_query.query_time_ms metric with initial data.
func (m *metricDNSQueryQueryTimeMs) init() {
	m.data.SetName("dns_query.query_time_ms")
	m.data.SetDescription("The time taken to complete the DNS query in milliseconds. Zero on timeout or error.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricDNSQueryQueryTimeMs) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, dnsQueryDomainAttributeValue string, dnsQueryRcodeAttributeValue string, dnsQueryRecordTypeAttributeValue string, dnsQueryResultAttributeValue string, dnsQueryServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("dns_query.domain", dnsQueryDomainAttributeValue)
	dp.Attributes().PutStr("dns_query.rcode", dnsQueryRcodeAttributeValue)
	dp.Attributes().PutStr("dns_query.record_type", dnsQueryRecordTypeAttributeValue)
	dp.Attributes().PutStr("dns_query.result", dnsQueryResultAttributeValue)
	dp.Attributes().PutStr("dns_query.server", dnsQueryServerAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricDNSQueryQueryTimeMs) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricDNSQueryQueryTimeMs) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricDNSQueryQueryTimeMs(cfg MetricConfig) metricDNSQueryQueryTimeMs {
	m := metricDNSQueryQueryTimeMs{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricDNSQueryRcodeValue struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills dns_query.rcode_value metric with initial data.
func (m *metricDNSQueryRcodeValue) init() {
	m.data.SetName("dns_query.rcode_value")
	m.data.SetDescription("The numeric DNS response code (rcode). 0=NOERROR, 3=NXDOMAIN, etc. Zero on timeout or error.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricDNSQueryRcodeValue) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, dnsQueryDomainAttributeValue string, dnsQueryRcodeAttributeValue string, dnsQueryRecordTypeAttributeValue string, dnsQueryResultAttributeValue string, dnsQueryServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("dns_query.domain", dnsQueryDomainAttributeValue)
	dp.Attributes().PutStr("dns_query.rcode", dnsQueryRcodeAttributeValue)
	dp.Attributes().PutStr("dns_query.record_type", dnsQueryRecordTypeAttributeValue)
	dp.Attributes().PutStr("dns_query.result", dnsQueryResultAttributeValue)
	dp.Attributes().PutStr("dns_query.server", dnsQueryServerAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricDNSQueryRcodeValue) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricDNSQueryRcodeValue) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricDNSQueryRcodeValue(cfg MetricConfig) metricDNSQueryRcodeValue {
	m := metricDNSQueryRcodeValue{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricDNSQueryResultCode struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills dns_query.result_code metric with initial data.
func (m *metricDNSQueryResultCode) init() {
	m.data.SetName("dns_query.result_code")
	m.data.SetDescription("The result code of the DNS query: 0=success, 1=timeout, 2=error.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricDNSQueryResultCode) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, dnsQueryDomainAttributeValue string, dnsQueryRcodeAttributeValue string, dnsQueryRecordTypeAttributeValue string, dnsQueryResultAttributeValue string, dnsQueryServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("dns_query.domain", dnsQueryDomainAttributeValue)
	dp.Attributes().PutStr("dns_query.rcode", dnsQueryRcodeAttributeValue)
	dp.Attributes().PutStr("dns_query.record_type", dnsQueryRecordTypeAttributeValue)
	dp.Attributes().PutStr("dns_query.result", dnsQueryResultAttributeValue)
	dp.Attributes().PutStr("dns_query.server", dnsQueryServerAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricDNSQueryResultCode) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricDNSQueryResultCode) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricDNSQueryResultCode(cfg MetricConfig) metricDNSQueryResultCode {
	m := metricDNSQueryResultCode{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricDNSQueryQueryTimeMs      metricDNSQueryQueryTimeMs
	metricDNSQueryRcodeValue       metricDNSQueryRcodeValue
	metricDNSQueryResultCode       metricDNSQueryResultCode
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricDNSQueryQueryTimeMs:      newMetricDNSQueryQueryTimeMs(mbc.Metrics.DNSQueryQueryTimeMs),
		metricDNSQueryRcodeValue:       newMetricDNSQueryRcodeValue(mbc.Metrics.DNSQueryRcodeValue),
		metricDNSQueryResultCode:       newMetricDNSQueryResultCode(mbc.Metrics.DNSQueryResultCode),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.SwOtelcolDnsqueryDomain.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.dnsquery.domain"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolDnsqueryDomain.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolDnsqueryDomain.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.dnsquery.domain"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolDnsqueryDomain.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolDnsqueryRecordType.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.dnsquery.record_type"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolDnsqueryRecordType.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolDnsqueryRecordType.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.dnsquery.record_type"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolDnsqueryRecordType.MetricsExclude)
	}
	if mbc.ResourceAttributes.SwOtelcolDnsqueryServer.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["sw.otelcol.dnsquery.server"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolDnsqueryServer.MetricsInclude)
	}
	if mbc.ResourceAttributes.SwOtelcolDnsqueryServer.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["sw.otelcol.dnsquery.server"] = filter.CreateFilter(mbc.ResourceAttributes.SwOtelcolDnsqueryServer.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricDNSQueryQueryTimeMs.emit(ils.Metrics())
	mb.metricDNSQueryRcodeValue.emit(ils.Metrics())
	mb.metricDNSQueryResultCode.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordDNSQueryQueryTimeMsDataPoint adds a data point to dns_query.query_time_ms metric.
func (mb *MetricsBuilder) RecordDNSQueryQueryTimeMsDataPoint(ts pcommon.Timestamp, val float64, dnsQueryDomainAttributeValue string, dnsQueryRcodeAttributeValue string, dnsQueryRecordTypeAttributeValue string, dnsQueryResultAttributeValue string, dnsQueryServerAttributeValue string) {
	mb.metricDNSQueryQueryTimeMs.recordDataPoint(mb.startTime, ts, val, dnsQueryDomainAttributeValue, dnsQueryRcodeAttributeValue, dnsQueryRecordTypeAttributeValue, dnsQueryResultAttributeValue, dnsQueryServerAttributeValue)
}

// RecordDNSQueryRcodeValueDataPoint adds a data point to dns_query.rcode_value metric.
func (mb *MetricsBuilder) RecordDNSQueryRcodeValueDataPoint(ts pcommon.Timestamp, val int64, dnsQueryDomainAttributeValue string, dnsQueryRcodeAttributeValue string, dnsQueryRecordTypeAttributeValue string, dnsQueryResultAttributeValue string, dnsQueryServerAttributeValue string) {
	mb.metricDNSQueryRcodeValue.recordDataPoint(mb.startTime, ts, val, dnsQueryDomainAttributeValue, dnsQueryRcodeAttributeValue, dnsQueryRecordTypeAttributeValue, dnsQueryResultAttributeValue, dnsQueryServerAttributeValue)
}

// RecordDNSQueryResultCodeDataPoint adds a data point to dns_query.result_code metric.
func (mb *MetricsBuilder) RecordDNSQueryResultCodeDataPoint(ts pcommon.Timestamp, val int64, dnsQueryDomainAttributeValue string, dnsQueryRcodeAttributeValue string, dnsQueryRecordTypeAttributeValue string, dnsQueryResultAttributeValue string, dnsQueryServerAttributeValue string) {
	mb.metricDNSQueryResultCode.recordDataPoint(mb.startTime, ts, val, dnsQueryDomainAttributeValue, dnsQueryRcodeAttributeValue, dnsQueryRecordTypeAttributeValue, dnsQueryResultAttributeValue, dnsQueryServerAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
