# Example of an invalid configuration that should fail validation
connectors:
  solarwindsentity:
    source_prefix: "source."
    destination_prefix: "dest."
    expiration_policy:
      enabled: true
      # Missing mandatory interval when enabled is true
    schema:
      entities: [] # Invalid: must contain at least 1 item
      events:
        entities:
          - action: "invalid_action" # Invalid: must be 'update' or 'delete'
            context: invalid_context # Invalid: must be 'log' or 'metric'
            type: NonExistentType # Invalid: must be defined in schema.entities
        relationships:
          - action: "delete"
            context: metric
            type: CommunicatesWith
            # Missing mandatory source_entity and destination_entity
