# Example of a valid configuration that should pass validation
connectors:
  solarwindsentity:
    source_prefix: "source." # Optional
    destination_prefix: "dest." # Optional
    expiration_policy: # Optional
      enabled: true # Optional
      interval: 5m # Mandatory if enabled true
    schema: # Mandatory
      entities: # Mandatory (at least 1 item)
        - entity: KubernetesPod # Mandatory
          id: # Mandatory (at least 1 item)
            - k8s.pod.name
            - k8s.namespace.name
            - sw.k8s.cluster.uid
          attributes: # Optional
            - sw.k8s.pod.status
        - entity: KubernetesDeployment # Additional entity for relationships
          id:
            - k8s.deployment.name
            - k8s.namespace.name
            - sw.k8s.cluster.uid
      events: # Mandatory
        entities: # Mandatory (at least 1 item)
          - action: "update" # Mandatory
            context: log # Mandatory
            type: KubernetesPod # Mandatory
            conditions: # Optional
              - resource.attributes["k8s.pod.name"] != nil
        relationships: # Optional
          - action: "delete" # Mandatory
            context: metric # Mandatory
            type: CommunicatesWith # Mandatory
            conditions: # Optional
              - metric.name == "k8s.tcp.bytes"
            source_entity: KubernetesPod # Mandatory
            destination_entity: KubernetesDeployment # Mandatory
            attributes: # Optional
              - sw.connection.status
