name: Technical improvement
description: Suggest a general technical improvement for this project
labels: ["enhancement", "maintenance", "needs triage"]
type: Task
body:
  - type: textarea
    attributes:
      label: Is your suggestion related to a general technical or maintenance issue? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
