// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for solarwinds resource attributes.
type ResourceAttributesConfig struct {
	HostID                           ResourceAttributeConfig `mapstructure:"host.id"`
	HostName                         ResourceAttributeConfig `mapstructure:"host.name"`
	OsType                           ResourceAttributeConfig `mapstructure:"os.type"`
	SwOtelcolCollectorEntityCreation ResourceAttributeConfig `mapstructure:"sw.otelcol.collector.entity_creation"`
	SwOtelcolCollectorName           ResourceAttributeConfig `mapstructure:"sw.otelcol.collector.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		HostID: ResourceAttributeConfig{
			Enabled: false,
		},
		HostName: ResourceAttributeConfig{
			Enabled: false,
		},
		OsType: ResourceAttributeConfig{
			Enabled: false,
		},
		SwOtelcolCollectorEntityCreation: ResourceAttributeConfig{
			Enabled: false,
		},
		SwOtelcolCollectorName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}
