// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8seventgeneration")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector-contrib/processor/k8seventgenerationprocessor"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
