name: "Nightly govulncheck"

on:
  push:
    branches: [ "chore/add-govulncheck" ]
  pull_request:
    branches: [ "chore/add-govulncheck" ]
  schedule:
    - cron: '*/1 * * * *'

jobs:
    nightly-vulncheck-modules:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Go vulnerabilities check
              run: |
                  make ci-vulncheck-nightly-modules title="SolarWinds Otel Collector Contrib Vulnerabilities (Public)" 2>&1
