name: Release Components

on:
  push:
    paths:
      - 'pkg/version/version.go'
    branches:
      - main
      - 'release/**'

  workflow_dispatch:

jobs:
  release_checks:
    name: Release Checks
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get Current Tag
        id: get-tag
        run: echo "tag=$(grep -oP '(?<=const Version = ")[^"]+' "./pkg/version/version.go")" >> $GITHUB_OUTPUT
      - name: Verify that release does not already exist
        env:
          # for gh cli
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make validate-release-uniqueness tag=${{ steps.get-tag.outputs.tag }}

#  build_and_test:
#    name: Build and Test
#    uses: ./.github/workflows/buildAndTest.yml
#    secrets: inherit

  create_release:
    runs-on: ubuntu-latest
    name: Create GitHub Release
    needs:
      - release_checks
#      - build_and_test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Find Previous Tag
        run: |
          PREVIOUS_TAG=$(make get-previous-tag)
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

#      - name: Create GitHub Release
#        env:
#          # for gh cli
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: make create-github-release current_tag=${{ needs.release_checks.outputs.image_tag }} previous_tag=${{ env.PREVIOUS_TAG }}
#      - name: Tag Go packages on GitHub
#        run: |
#          FOLDERS="./exporter ./extension ./pkg ./receiver ./connector ./processor ./internal"
#          EXCLUDED_FOLDERS="./internal/tools/"
#          make tag-github-packages folders="$FOLDERS" version=${{ needs.release_checks.outputs.image_tag }} excluded_folders="$EXCLUDED_FOLDERS"
