name: Release Components

on:
  push:
    paths:
      - 'pkg/version/version.go'
    branches:
      - main
      - 'release/**'

  workflow_dispatch:

jobs:      
  govulncheck-modules: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Go vulnerabilities check
        run: |
          make ci-vulncheck-modules 2>&1

  build_and_test:
    name: Build and Test
    permissions:
      contents: read
    uses: ./.github/workflows/buildAndTest.yml
    secrets: inherit

  tag_components:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Tag Components
    needs:
      - build_and_test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Get Current Version
        id: get-version
        run: echo "version=$(grep -oP '(?<=const Version = ")[^"]+' "./pkg/version/version.go")" >> $GITHUB_OUTPUT

      - name: Tag Repository and Go packages on GitHub
        run: |
          TAG="v${{ steps.get-version.outputs.version }}"
          FOLDERS="./exporter ./extension ./pkg ./receiver ./connector ./processor ./internal"
          make tag-repository folders="$FOLDERS" tag="$TAG" excluded_folders="$EXCLUDED_FOLDERS"
